version: "3"
services: 
    perf:
      build: ./
      privileged: true
      pid: host
      cap_add: 
      - SYS_ADMIN
      volumes: 
      - "/tmp:/tmp"
      - "./build:/usr/share/async-profiler/build"
    tomcat:
      image: tomcat
      ports:
      - "8080:8080"
      cap_add: 
      - ALL
      volumes: 
      - "/tmp:/tmp"
      - "./build:/usr/share/async-profiler/build"