version: "3"
services: 
    perf:
      build: ./
      privileged: true
      pid: host
      cap_add: 
      - SYS_ADMIN
      volumes: 
      - "/tmp:/tmp"
    tomcat:
      image: tomcat
      ports:
      - "8080:8080"
      volumes: 
      - "/tmp:/tmp"
      - "./build:/opt/java-perf-tools/build"